### ISSUE TITLE
Cannot build / E0507

### ISSUE THREAD

**Issue by mrjetas** [maboroshinokiseki/My-My-Passport-Utility#1]
Compiling wd_vsc v0.2.0 (/home/gedas/My-My-Passport-Utility/wd_vsc)
error[E0507]: cannot move out of `self.encryption_status_data` which is behind a shared reference
  --> **wd_vsc/src/native/encryption_status.rs:57:5**
   |
55 | #[derive(Debug)]
   |          ----- in this derive macro expansion
56 | struct EncryptionStatusDataWithCiphers {
57 |     encryption_status_data: EncryptionStatusData,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.encryption_status_data` has type `EncryptionStatusData`, which does not implement the `Copy` trait
   |
   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by maboroshinokiseki** [comment]
Sorry for the very late reply, it's been fixed now
